// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Standardized Supabase environment configuration
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

// HARD GUARD - NO SILENT FAIL
if (!supabaseUrl || !supabaseKey) {
  throw new Error("Supabase ENV not injected at build time: check VITE_SUPABASE_URL / VITE_SUPABASE_ANON_KEY");
}

// Dev-only confirmation (boolean only, not exposing values)
if (import.meta.env.DEV) {
  console.log('Supabase client initialized:', !!supabaseUrl && !!supabaseKey);
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});